"""Product configuration module"""

from enum import Enum


class ProductCategory(Enum):
    """Product categories"""

    AMAZON_DEVICES_ACCESSORIES = "Amazon Devices & Accessories"
    APPLIANCES = "Appliances"
    ARTS_CRAFTS_SEWING = "Arts, Crafts & Sewing"
    AUDIBLE_BOOKS_ORIGINALS = "Audible Books & Originals"
    AUTOMOTIVE = "Automotive"
    BABY_PRODUCTS = "Baby Products"
    BEAUTY_PERSONAL_CARE = "Beauty & Personal Care"
    BOOKS = "Books"
    CAR_VEHICLE_ELECTRONICS = "Car & Vehicle Electronics"
    CDS_VINYL = "CDs & Vinyl"
    CELL_PHONES_ACCESSORIES = "Cell Phones & Accessories"
    CLOTHING_SHOES_JEWELRY = "Clothing, Shoes & Jewelry"
    COLLECTIBLES_FINE_ART = "Collectibles & Fine Art"
    DINING_ENTERTAINING = "Dining & Entertaining"
    ELECTRONICS = "Electronics"
    FOOD_SERVICE_EQUIPMENT_SUPPLIES = "Food Service Equipment & Supplies"
    GIFT_CARDS = "Gift Cards"
    GRILLS_OUTDOOR_COOKING = "Grills & Outdoor Cooking"
    GROCERY_GOURMET_FOOD = "Grocery & Gourmet Food"
    HANDMADE_PRODUCTS = "Handmade Products"
    HEALTH_HOUSEHOLD = "Health & Household"
    HEAVY_DUTY_COMMERCIAL_VEHICLE_EQUIPMENT = (
        "Heavy Duty & Commercial Vehicle Equipment"
    )
    HOME_KITCHEN = "Home & Kitchen"
    HUNTING_FISHING = "Hunting & Fishing"
    INDUSTRIAL_SCIENTIFIC = "Industrial & Scientific"
    INSTRUMENT_ACCESSORIES = "Instrument Accessories"
    JANITORIAL_SANITATION_SUPPLIES = "Janitorial & Sanitation Supplies"
    KINDLE_EBOOKS = "Kindle eBooks"
    KINDLE_STORE = "Kindle Store"
    KITCHEN_DINING = "Kitchen & Dining"
    LAB_SCIENTIFIC_PRODUCTS = "Lab & Scientific Products"
    LIGHTING_ASSEMBLIES_ACCESSORIES = "Lighting Assemblies & Accessories"
    LIGHTS_LIGHTING_ACCESSORIES = "Lights & Lighting Accessories"
    MAGAZINE_SUBSCRIPTIONS = "Magazine Subscriptions"
    MEDICAL_SUPPLIES_EQUIPMENT = "Medical Supplies & Equipment"
    MOBILITY_DAILY_LIVING_AIDS = "Mobility & Daily Living Aids"
    MOTORCYCLE_POWERSPORTS = "Motorcycle & Powersports"
    MOVIES_TV = "Movies & TV"
    MUSICAL_INSTRUMENTS = "Musical Instruments"
    OFFICE_ELECTRONICS = "Office Electronics"
    OFFICE_PRODUCTS = "Office Products"
    OUTDOOR_POWER_TOOLS = "Outdoor Power Tools"
    PATIO_LAWN_GARDEN = "Patio, Lawn & Garden"
    PERFORMANCE_PARTS_ACCESSORIES = "Performance Parts & Accessories"
    PET_SUPPLIES = "Pet Supplies"
    POWER_HAND_TOOLS = "Power & Hand Tools"
    POWER_TOOL_PARTS_ACCESSORIES = "Power Tool Parts & Accessories"
    PROFESSIONAL_DENTAL_SUPPLIES = "Professional Dental Supplies"
    REMOTE_APP_CONTROLLED_VEHICLE_PARTS = "Remote & App Controlled Vehicle Parts"
    REMOTE_APP_CONTROLLED_VEHICLES = "Remote & App Controlled Vehicles & Parts"
    RESTAURANT_APPLIANCES_EQUIPMENT = "Restaurant Appliances & Equipment"
    SAFETY_SECURITY = "Safety & Security"
    SHOE_JEWELRY_WATCH_ACCESSORIES = "Shoe, Jewelry & Watch Accessories"
    SMALL_APPLIANCE_PARTS_ACCESSORIES = "Small Appliance Parts & Accessories"
    SOFTWARE = "Software"
    SPORTS_OUTDOOR_RECREATION_ACCESSORIES = "Sports & Outdoor Recreation Accessories"
    SPORTS_OUTDOORS = "Sports & Outdoors"
    TOOLS_HOME_IMPROVEMENT = "Tools & Home Improvement"
    TOYS_GAMES = "Toys & Games"
    VIDEO_GAMES = "Video Games"